on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          verbose: true
          fqbn: "esp8266:esp8266:LOLIN(WEMOS) D1 mini Pro"
          platforms: |
            - name: esp8622:esp8622
            - source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              name: esp8622:esp8622
          sketch-paths: |
            - Firmware/sm-esp8266
          libraries: |
            - name: WiFiManager
            - name: ArduinoJson
            - name: PubSubClient

  
          
