on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name arduino:esp8266
            - source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          fqbn: arduino:esp8266:d1_mini
          sketch-paths: |
            - Firmware/sm-esp8266
          libraries: |
            - name: WiFiManager
            - name: JsonArduino
            - name: PubSubClient

  
          
