on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ardiuno/compile-sketches@v1
        with:
          fqbn: ardiuno:esp8266:d1_mini
          sketch-paths: |
            - Firmware/sm-esp8266
          libraries: |
            - name: WiFiManager
            - name: JsonArduino
            - name: PubSubClient

  
          
