name: release-sm-esp8266
on: [push, pull_request]
jobs:
  release-sm-esp8266:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

      - name: Install ESP8266 platform
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Install Libraries
        run: |
          arduino-cli lib install WiFiManager
          arduino-cli lib install ArduinoJson
          arduino-cli lib install PubSubClient

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:d1_mini_pro Firmware/sm-esp8266 -v -e

      - name: List files
        run: |
          ls -l Firmware/sm-esp8266/build/esp8266.esp8266.d1_mini_pro
